# Generated by Django 2.0.4 on 2018-04-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nicething',
            name='reported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
