# Generated by Django 2.0.4 on 2018-04-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180418_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='nicething',
            name='reported_reason',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
