# Generated by Django 2.0.4 on 2018-04-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180419_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nicething',
            name='reported_reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
